[toolchain]
# channel = "nightly-2026-04-01"
channel = "nightly"
profile = "minimal"
components = [
  "cargo",
  "clippy",
  "miri",
  "rust-analyzer",
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
